name = "product-ltv-app"
main = "worker/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "client/dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "product-ltv-db"
database_id = "60aa8281-7209-4857-bb24-979e33294b7b"
